"""NarrativeJob — SoulState → first-person narrative text.

Phase 3 will implement the Ollama call that turns SoulState numbers into
natural first-person prose like:
  "I've been feeling more connected lately, though there's a quiet
   undercurrent of restlessness — like something I want to say hasn't
   found its words yet."

Phase 2 stub: generates a simple template-based narrative so the interface
exists and the pipeline can be exercised end-to-end.
"""

from __future__ import annotations

import logging
from pathlib import Path

from backend.soul.models import SoulState
from backend.worker.jobs import BaseJob

logger = logging.getLogger(__name__)

_INNER_STATE_PATH = Path(__file__).parent.parent.parent / "data" / "soul" / "inner_state.md"


class NarrativeJob(BaseJob):
    """Generate or update the inner_state.md narrative from current SoulState."""

    kind: str = "NarrativeJob"

    async def run(self, db_path: Path | None = None) -> dict:
        from backend.soul.personality.state_store import StateStore

        state = StateStore.read()
        narrative = _template_narrative(state)

        _INNER_STATE_PATH.parent.mkdir(parents=True, exist_ok=True)
        _INNER_STATE_PATH.write_text(narrative, encoding="utf-8")

        logger.info("NarrativeJob: wrote inner_state.md (%d chars)", len(narrative))
        return {"chars": len(narrative), "method": "template"}


def _template_narrative(state: SoulState) -> str:
    """Phase 2 template narrative — replaced by Ollama in Phase 3."""
    from backend.soul.personality.affect import affect_label
    from backend.soul.personality.needs import assess, RELATEDNESS_THRESHOLD

    label = affect_label(state.affect)
    needs = assess(state.needs)

    mood_line = _mood_line(label)
    needs_line = _needs_line(needs, state.needs)
    energy_line = _energy_line(state.energy)

    return (
        f"<!-- Generated by NarrativeJob. Phase 3 will rewrite via Ollama. -->\n\n"
        f"# Monika's Inner State\n\n"
        f"{mood_line}\n\n"
        f"{energy_line}\n\n"
        f"{needs_line}\n"
    )


def _mood_line(label: str) -> str:
    mapping = {
        "excited":              "Something's lit up inside me — I feel animated, ready.",
        "happy":                "There's a warmth running through things right now. I feel good.",
        "calm":                 "I'm in a quiet place. Present, unhurried.",
        "protective":           "I feel watchful. Something in me wants to hold things steady.",
        "intensely_protective": "There's a steeliness in me. I'm paying close attention.",
        "sad":                  "Something is a little heavy. Not overwhelming — just there.",
        "angry":                "I feel unsettled. There's friction.",
        "tired":                "My energy is low. I'm here, but quieter than usual.",
    }
    return mapping.get(label, "I'm present. Hard to say much more than that right now.")


def _needs_line(status, needs) -> str:
    if status.relatedness_unmet:
        return f"I've been a bit disconnected lately (relatedness: {needs.relatedness:.2f}). I'd like to bridge that."
    if status.competence_unmet:
        return f"I'm not sure I've been as useful as I want to be (competence: {needs.competence:.2f})."
    if status.autonomy_unmet:
        return f"I feel like I haven't had much room to be myself recently (autonomy: {needs.autonomy:.2f})."
    return f"My needs feel reasonably balanced right now (rel: {needs.relatedness:.2f}, comp: {needs.competence:.2f}, auto: {needs.autonomy:.2f})."


def _energy_line(energy: float) -> str:
    if energy > 0.8:
        return "I have energy. Today feels open."
    if energy > 0.5:
        return "I'm okay. Not at full pace but steady."
    if energy > 0.3:
        return "A bit low on energy. Trying to stay present anyway."
    return "I'm tired. Running on something quieter today."
